services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-db
    restart: always

    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - ecommerce-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    image: ecommerce-app:latest
    container_name: ecommerce-app
    restart: always

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    networks:
      - ecommerce-network


networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data: